name: Demo workflow

on: workflow_dispatch

jobs:
    print-stuff:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checout@v4
            - run: pwd
            - run: ls
    
